%%
%% This is file `AMbrief.cls',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% AMbrief.dtx  (with options: `class')
%% --------------------------------------------------------------------------------
%% AMbrief <!AMreleaseVersion!> --- Class of the AMlatex-Bundle for letters
%% E-mail: romain.pennec@tum.de
%% Released under the LaTeX Project Public License v1.3c or later
%% See http://www.latex-project.org/lppl.txt
%% --------------------------------------------------------------------------------
%% 
\RequirePackage{AMgit}
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{AMbrief}[\AMinsertGitDate{} \AMinsertGitVersion{} AM TUM letter]
\ClassInfo{AMbrief}{Document class of the Institute of Applied Mechanics}
\pdfmapfile{+tumhelv.map}
\LoadClass[MW,ngerman]{tumbrief}
\Institut{Lehrstuhl f\"ur Angewandte Mechanik}
\RequirePackage{AMref}
\AMwritePdfMetaProperties{Created with AMbrief}
%% 
%% Copyright (c) 2008-2009 Rechen-Gilde <tum@rechengil.de>
%% Copyright (C) 2015-2016 by R. Pennec <romain.pennec@tum.de>
%% 
%% This work may be distributed and/or modified under the
%% conditions of the LaTeX Project Public License (LPPL), either
%% version 1.3c of this license or (at your option) any later
%% version.  The latest version of this license is in the file:
%% 
%% http://www.latex-project.org/lppl.txt
%% 
%% This work is "maintained" (as per LPPL maintenance status) by
%% Romain Pennec.
%% 
%% This work consists of the file  AMbrief.dtx
%% and the derived files           AMbrief.ins,
%%                                 AMbrief.pdf and
%%                                 AMbrief.cls.
%%
%% End of file `AMbrief.cls'.
